stages:
   - Building & migration

build:
  stage: Building & migration
  commands:
     - ls
     - jar -cvf helloworld.war *.jsp WEB-INF
     - mv -f helloworld.war target/

pre-build:
  script:
    - ls

post-build:
  script:
    - ls -la

