stages:
   - Building & migration

build:
  stage: Building & migration
  commands:
     - ls
     - jar -cvf helloworld.war *.jsp WEB-INF
     - mv -f helloworld.war target/

pre-build:
  script:
    - ls

post-build:
  script:
    - ls -la

projects:
    - name: Maven
      build-platform: maven:latest as build-env
      build-commands:
        - apt-get update && apt-get install git
        - CHECKOUT
        - jar -cvf helloworld.war *.jsp WEB-INF
        - mv helloworld.war /tmp/helloworld.war
      platform: tomcat:latest
      copy:
         - --from=build-env /tmp/helloworld.war /usr/local/tomcat/webapps
      service:
        - name: devops-maven
          port: 8080
      type:
         - name: deployment


